image: "rust:latest"

stages:
  - build
  - test

build:day-1:
  stage: build
  script:
    - cd day1
    - cargo build --release

build:day-2:
  stage: build
  script:
    - cd day2
    - cargo build --release

run:day-1:
  stage: test
  script:
    - cd day1
    - cargo run

run:day-2:
  stage: test
  script:
    - cd day2
    - cargo run
