image: "rust:latest"

stages:
  - build
  - test

build:day-1:
  stage: build
  script:
    - cd day1
    - cargo build --release

build:day-2:
  stage: build
  script:
    - cd day2
    - cargo build --release

build:day-4:
  stage: build
  script:
    - cd day4
    - cargo build --release

build:day-5:
  stage: build
  script:
    - cd day5
    - cargo build --release

build:day-7:
  stage: build
  script:
    - cd day7
    - cargo build --release

build:day-8:
  stage: build
  script:
    - cd day8
    - cargo build --release

run:day-1:
  stage: test
  script:
    - cd day1
    - cargo run

run:day-2:
  stage: test
  script:
    - cd day2
    - cargo run

run:day-4:
  stage: test
  script:
    - cd day4
    - cargo run

run:day-5:
  stage: test
  script:
    - cd day5
    - echo '1' | cargo run
    - echo '5' | cargo run

run:day-7:
  stage: test
  script:
    - cd day7
    - cargo run

run:day-8:
  stage: test
  script:
    - cd day8
    - cargo run
