image: "rust:latest"

stages:
  - build
  - test

build:day-1:
  stage: build
  script:
    - cd day1
    - cargo build --release

build:day-2:
  stage: build
  script:
    - cd day2
    - cargo build --release

build:day-3:
  stage: build
  script:
    - cd day3
    - cargo build --release

build:day-4:
  stage: build
  script:
    - cd day4
    - cargo build --release

build:day-5:
  stage: build
  script:
    - cd day5
    - cargo build --release

build:day-7:
  stage: build
  script:
    - cd day7
    - cargo build --release

build:day-8:
  stage: build
  script:
    - cd day8
    - cargo build --release

build:day-9:
  stage: build
  script:
    - cd day9
    - cargo build --release

build:day-10:
  stage: build
  script:
    - cd day10
    - cargo build --release

build:day-11:
  stage: build
  script:
    - cd day11
    - cargo build --release

build:day-12:
  stage: build
  script:
    - cd day12
    - cargo build --release

build:day-13:
  stage: build
  script:
    - cd day13
    - cargo build --release

build:day-14:
  stage: build
  script:
    - cd day14
    - cargo build --release

run:day-1:
  stage: test
  script:
    - cd day1
    - cargo run --release

run:day-2:
  stage: test
  script:
    - cd day2
    - cargo run --release

run:day-3:
  stage: test
  script:
    - cd day3
    - cargo run --release

run:day-4:
  stage: test
  script:
    - cd day4
    - cargo run --release

run:day-5:
  stage: test
  script:
    - cd day5
    - echo '1' | cargo run --release
    - echo '5' | cargo run --release

run:day-7:
  stage: test
  script:
    - cd day7
    - cargo run --release

run:day-8:
  stage: test
  script:
    - cd day8
    - cargo run --release

run:day-9:
  stage: test
  script:
    - cd day9
    - cargo run --release

run:day-10:
  stage: test
  script:
    - cd day9
    - cargo run --release

run:day-11:
  stage: test
  script:
    - cd day11
    - cargo run --release

run:day-12:
  stage: test
  script:
    - cd day12
    - cargo run --release

run:day-13:
  stage: test
  script:
    - cd day13
    - cargo run --release

run:day-14:
  stage: test
  script:
    - cd day14
    - cargo run --release
