[package]
name = "day22"
version = "0.1.0"
authors = ["J.M. Thiessen <jacob@x0rz3q.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.2" 
num-traits = "0.2.8"
num = "0.2.0"
